/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecnikRouteImport } from './routes/recnik'
import { Route as ORecnikuRouteImport } from './routes/o-recniku'
import { Route as KvizRouteImport } from './routes/kviz'
import { Route as IndexRouteImport } from './routes/index'

const RecnikRoute = RecnikRouteImport.update({
  id: '/recnik',
  path: '/recnik',
  getParentRoute: () => rootRouteImport,
} as any)
const ORecnikuRoute = ORecnikuRouteImport.update({
  id: '/o-recniku',
  path: '/o-recniku',
  getParentRoute: () => rootRouteImport,
} as any)
const KvizRoute = KvizRouteImport.update({
  id: '/kviz',
  path: '/kviz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kviz': typeof KvizRoute
  '/o-recniku': typeof ORecnikuRoute
  '/recnik': typeof RecnikRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kviz': typeof KvizRoute
  '/o-recniku': typeof ORecnikuRoute
  '/recnik': typeof RecnikRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kviz': typeof KvizRoute
  '/o-recniku': typeof ORecnikuRoute
  '/recnik': typeof RecnikRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kviz' | '/o-recniku' | '/recnik'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kviz' | '/o-recniku' | '/recnik'
  id: '__root__' | '/' | '/kviz' | '/o-recniku' | '/recnik'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KvizRoute: typeof KvizRoute
  ORecnikuRoute: typeof ORecnikuRoute
  RecnikRoute: typeof RecnikRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recnik': {
      id: '/recnik'
      path: '/recnik'
      fullPath: '/recnik'
      preLoaderRoute: typeof RecnikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-recniku': {
      id: '/o-recniku'
      path: '/o-recniku'
      fullPath: '/o-recniku'
      preLoaderRoute: typeof ORecnikuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kviz': {
      id: '/kviz'
      path: '/kviz'
      fullPath: '/kviz'
      preLoaderRoute: typeof KvizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KvizRoute: KvizRoute,
  ORecnikuRoute: ORecnikuRoute,
  RecnikRoute: RecnikRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
